### ISSUE TITLE
_this3.jaxElement not defined when mathjax sourced locally

### ISSUE THREAD

**Issue by ostcrom** [ianlucas/mathjax-editor-keyboard#2]
I have a strange issue, I can load the demo html no problem but when I change the source of MathJax from the CDN to a local copy, the script breaks and I get "_this3.jaxElement is undefined" in the console. I have done some troubleshooting, and as the error suggest, jaxElement is not defined because a.getAllJax($display) call farther up returns an empty array instead of our Jax elements.

Seems strange it would not work correctly when using a locally hosted copy and work OK from the CDN, I even used wget to pull a copy from the CDN. I am hosting using via "static" directories in express if that makes a difference.

Any ideas?

**Comment by pkra** [comment]
> I even used wget to pull a copy from the CDN

MathJax is much larger than `MathJax.js`, cf. http://docs.mathjax.org/en/latest/installation.html

**Comment by ostcrom** [comment]
Aha, this should be the answer I need. In the off chance it does not work I will figure out what I am doing wrong from there. Thanks! 👍

**Comment by ostcrom** [comment]
Aha, this should be the answer I need. In the off chance it does not work I will figure out what I am doing wrong from there. Thanks! 👍
